// Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
#include<iostream>
using namespace std;

void subSeq(string str,int n){
    //base case 
    if()
   
}
int main(){
    
    string str= "hello";

    subSeq(str,str.length());

return 0;
}